# Gunakan image Node.js
FROM node:18

# Set direktori kerja
WORKDIR /app

# Salin file package dan install dependencies
COPY package*.json ./
RUN npm install

# Salin semua file proyek
COPY . .

# Buka port (ubah jika backend pakai port lain)
EXPOSE 3000

# Jalankan aplikasi
CMD ["npm", "start"]